INSERT INTO PRODUCT VALUES (1, 'Apple', 35, FALSE, NULL, NULL, NULL);
INSERT INTO PRODUCT VALUES (2, 'Banana', 20, FALSE, NULL, NULL, NULL);
INSERT INTO PRODUCT VALUES (3, 'Lime', 15, TRUE, 'Buy 3 at the cost of 2', 3, 2);
INSERT INTO PRODUCT VALUES (4, 'Melon', 50, TRUE, 'Buy 1 Get 1 Free', 2, 1);