INSERT INTO PRODUCT VALUES (1, 'apple', 35, FALSE, NULL, NULL, NULL);
INSERT INTO PRODUCT VALUES (2, 'banana', 20, FALSE, NULL, NULL, NULL);
INSERT INTO PRODUCT VALUES (3, 'lime', 15, TRUE, 'Buy 3 at the cost of 2', 3, 2);
INSERT INTO PRODUCT VALUES (4, 'melon', 50, TRUE, 'Buy 1 Get 1 Free', 2, 1);